### ISSUE TITLE
17. Повторное трестирование программы

### ISSUE THREAD

**Issue by LudwigMintus** [uvuv513851/Paint#17]

**Comment by Wyncher** [comment]
Снова протестировали. **Теперь работает** ещё лучше!

**Comment by Wyncher** [comment]
Снова протестировали. Теперь работает ещё лучше!

**Comment by thegotamaster** [comment]
Протестировали, работает.

**Comment by LudwigMintus** [comment]
После оптимизации приложение  работает идеально.

**Comment by uvuv513851** [comment]
Оптимизация пошла на пользу,  тестирование прошло успешно.
