### ISSUE TITLE
19. Разработка документации

### ISSUE THREAD

**Issue by LudwigMintus** [uvuv513851/Paint#19]

**Comment by Wyncher** [comment]
Документация подготовлена. Готовимся к с**даче**.

**Comment by Wyncher** [comment]
Документация подготовлена. Готовимся к сдаче.

**Comment by LudwigMintus** [comment]
Документация проекта готова.

**Comment by thegotamaster** [comment]
Документация разработана.

**Comment by uvuv513851** [comment]
Документация доведена до идеала.
