### ISSUE TITLE
4. Реализация выбора цвета

### ISSUE THREAD

**Issue by LudwigMintus** [uvuv513851/Paint#4]

**Comment by Wyncher** [comment]
Выбрали. Теперь и пользователь может выбрать
────────╠███████───███████╠─────────────
───────╠█████████─╠█████████────────────
───────█████████████████████╠───────────
──────╠██████████████████████───────────
──────███████████████████████───────────
──────███████████████████████╠──────────
──────███████████████████████╠──────────
──────███████████████████████───────────
──────╠██████████████████████───────────
──────╠█████████████████████╠───────────
───────█████████████████████────────────
───────╠███████████████████╠────────────
────────╠███████████──╠████─────────────
─────────██████████─────╠█╠─────────────
─────────╠████████──███─────────────────
──────────╠███████─╠█████───────────────
─────╠╠────╠██████─╠███████─────────────
──█████╠────╠█████╠─╠███████╠───────────
─╠███████╠█╠─╠█████╠──████████╠─────────
╠███████████╠──█████───╠████████╠───────
╠█████████████──╠██╠─────╠████████╠─────
─██████████████───────────█████████╠────
──╠█████████████╠───────╠███████████╠───
───╠█████████████████████████████████╠──
────╠█████████████████████████████████──
─────╠█████████████████████████████████─
───────████████████████████████████████╠
────────╠███████████████████████████████
─────────╠██████████████████████████████
───────────█████████████████████████████
────────────╠██████████████████████████─
───────────────────────────────╠██████──
─────────────────────────────────███╠───
─────────────────────────────────╠█╠────
